---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - crds/
  - manager/
  - frontend/
  - driver/

commonLabels:
  app.kubernetes.io/name: longhorn

configurations:
  - kustomizeconfig.yml

images:
  - name: wait-for
    newName: toolhippie/wait-for
    newTag: "latest"

  - name: longhorn-manager
    newName: longhornio/longhorn-manager
    newTag: "v1.1.1"
  - name: longhorn-frontend
    newName: longhornio/longhorn-ui
    newTag: "v1.1.1"
  - name: longhorn-engine
    newName: longhornio/longhorn-engine
    newTag: "v1.1.1"
  - name: longhorn-instancemanager
    newName: longhornio/longhorn-instance-manager
    newTag: "v1_20201216"
  - name: longhorn-sharemanager
    newName: longhornio/longhorn-share-manager
    newTag: "v1_20211020"
  - name: longhorn-backingmanager
    newName: longhornio/backing-image-manager
    newTag: "v1_20201216"

...
